#include <stdio.h>

#include "utils/assert.h"
#include "utils/strings.h"
#include "victoria/uiLayoutReader.h"

static Integer32 failureCount = 0;

static const char basicFixture[] =
    "# Generated by a test, not a UI editor\n"
    "<LEGACY clsid=GZWinGen iid=IGZWinGen id=0x11112222 area=(10,20,410,320) "
    "fillcolor=(1,2,3) caption=\"Test Root\" winflag_visible=no winflag_enabled=yes >\n"
    "\n"
    "<CHILDREN>\n"
    "   <LEGACY clsid=GZWinBMP iid=IGZWinBMP id=0x00000abc area=(0,0,900,700) "
    "image={499db772,ccc9af70} >\n"
    "   <LEGACY clsid=GZWinScrollo test iid=IGZWinScrollo test id=0x00009999 "
    "area=(5,5,60,25) containerimage={856ddbac,499db772,ccc30010} "
    "thumbimage={856ddbac,499db772,ccc30005} >\n"
    "   <LEGACY clsid=GZWinFlatRect iid=IGZWinFlatRect id=0x00000abd area=(50,60,150,160) "
    "fillcolor=(4,5,6) style=nofill >\n"
    "   <CHILDREN>\n"
    "      <LEGACY clsid=GZWinBtn iid=IGZWinBtn id=0x000000a3 area=(12,22,52,62) "
    "caption=\"Close\" image={0x856ddbac,0x499db772,0xccc30020} >\n"
    "   </CHILDREN>\n"
    "</CHILDREN>\n";

static const char emptyFixture[] = "# nothing but a comment\n\n";

static const char unclosedFixture[] =
    "<LEGACY clsid=GZWinGen area=(0,0,10,10) >\n"
    "<CHILDREN>\n"
    "   <LEGACY clsid=GZWinBtn area=(0,0,1,1) >\n";

static const char strayCloseFixture[] = "</CHILDREN>\n";

static const char childrenBeforeAnyElementFixture[] = "<CHILDREN>\n</CHILDREN>\n";

#define OVERFLOW_LINE_CAPACITY 2048UL
static char overflowFixture[(UI_LAYOUT_ELEMENT_LIMIT + 8UL) * OVERFLOW_LINE_CAPACITY];

static void buildOverflowFixture(Unsigned32 lineCount)
{
    Unsigned32 index;

    overflowFixture[0] = '\0';
    for (index = 0U; index < lineCount; index++)
    {
        stringAppend(overflowFixture, sizeof(overflowFixture),
                     "<LEGACY clsid=GZWinBMP area=(0,0,1,1) >\n");
    }
}

int main(void)
{
    UILayoutDescription description;
    UILayoutReadResult result;

    result = uiLayoutRead(&description, (const Unsigned8 *)basicFixture, stringLength(basicFixture));
    checkThat(&failureCount, "basic fixture reads OK", result == UI_LAYOUT_READ_OK);
    checkThat(&failureCount, "basic fixture has five elements", description.elementCount == 5U);
    checkThat(&failureCount, "basic fixture reports no overflow", description.elementsOverflow == 0U);

    if (description.elementCount == 5U)
    {
        const UIElement *root = &description.elements[0];
        const UIElement *bitmap = &description.elements[1];
        const UIElement *scrollbar = &description.elements[2];
        const UIElement *flatRect = &description.elements[3];
        const UIElement *button = &description.elements[4];
        Integer32 left;
        Integer32 top;
        Integer32 right;
        Integer32 bottom;

        checkThat(&failureCount, "root class name read", stringEquals(root->className, "GZWinGen"));
        checkThat(&failureCount, "root id read", root->hasID && root->id == 0x11112222UL);
        checkThat(&failureCount, "root area read",
                  root->areaLeft == 10 && root->areaTop == 20 && root->areaRight == 410 &&
                      root->areaBottom == 320);
        checkThat(&failureCount, "root fill colour read",
                  root->hasFillColor && root->fillRed == 1U && root->fillGreen == 2U && root->fillBlue == 3U);
        checkThat(&failureCount, "root caption read",
                  root->hasCaption && stringEquals(root->caption, "Test Root"));
        checkThat(&failureCount, "root winflag_visible=no read", root->visible == BOOLEAN_FALSE);
        checkThat(&failureCount, "root winflag_enabled=yes read", root->enabled == BOOLEAN_TRUE);
        checkThat(&failureCount, "root defaults to no parent", root->parentIndex == -1);

        checkThat(&failureCount, "bitmap is a child of the root", bitmap->parentIndex == 0);
        checkThat(&failureCount, "bitmap area is larger than its parent's, being parent-relative",
                  bitmap->areaRight > root->areaRight - root->areaLeft);
        checkThat(&failureCount, "bitmap image reference has two numbers",
                  bitmap->hasImage && bitmap->imageNumberCount == 2UL);
        checkThat(&failureCount, "bitmap image reference values read",
                  bitmap->imageNumbers[0] == 0x499db772UL && bitmap->imageNumbers[1] == 0xccc9af70UL);

        checkThat(&failureCount, "the embedded-space class name quirk rejoins only the clsid",
                  stringEquals(scrollbar->className, "GZWinScrollo test"));

        checkThat(&failureCount, "flat rect is a sibling of the bitmap, still under the root",
                  flatRect->parentIndex == 0);
        checkThat(&failureCount,
                  "flat rect reads style=nofill despite having its own fillcolor -- "
                  "nofill overrides a fill colour rather than requiring its absence",
                  flatRect->hasFillColor && flatRect->noFill == BOOLEAN_TRUE);

        checkThat(&failureCount, "button is a child of the flat rect, not the root",
                  button->parentIndex == 3);
        checkThat(&failureCount, "button caption read", stringEquals(button->caption, "Close"));
        checkThat(&failureCount, "button defaults to the fill style, omitting style= entirely",
                  button->noFill == BOOLEAN_FALSE);
        checkThat(&failureCount, "button image reference has three numbers", button->imageNumberCount == 3UL);
        checkThat(&failureCount, "button image reference values read",
                  button->imageNumbers[0] == 0x856ddbacUL && button->imageNumbers[1] == 0x499db772UL &&
                      button->imageNumbers[2] == 0xccc30020UL);

        checkThat(&failureCount, "root resolves invisible from its own flag",
                  uiLayoutIsVisible(&description, 0U) == BOOLEAN_FALSE);
        checkThat(&failureCount, "bitmap's own flag is visible=yes (the default), but its parent is not",
                  bitmap->visible == BOOLEAN_TRUE &&
                      uiLayoutIsVisible(&description, 1U) == BOOLEAN_FALSE);
        checkThat(&failureCount,
                  "button resolves invisible through two ancestors (flat rect, then root), "
                  "despite its own flag being visible=yes",
                  button->visible == BOOLEAN_TRUE &&
                      uiLayoutIsVisible(&description, 4U) == BOOLEAN_FALSE);

        uiLayoutGetAbsoluteArea(&description, 4U, &left, &top, &right, &bottom);
        checkThat(&failureCount, "absolute area sums every ancestor's own area",
                  left == 72 && top == 102 && right == left + 40 && bottom == top + 40);
    }

    result = uiLayoutRead(&description, (const Unsigned8 *)emptyFixture, stringLength(emptyFixture));
    checkThat(&failureCount, "a resource with no LEGACY tag reports empty, not malformed",
              result == UI_LAYOUT_READ_NO_ELEMENTS);

    result = uiLayoutRead(&description, (const Unsigned8 *)unclosedFixture, stringLength(unclosedFixture));
    checkThat(&failureCount, "a CHILDREN left open at end of file is reported, not silently closed",
              result == UI_LAYOUT_READ_UNBALANCED_CHILDREN);

    result = uiLayoutRead(&description, (const Unsigned8 *)strayCloseFixture, stringLength(strayCloseFixture));
    checkThat(&failureCount, "a closing CHILDREN with nothing open is reported",
              result == UI_LAYOUT_READ_UNBALANCED_CHILDREN);

    result = uiLayoutRead(&description, (const Unsigned8 *)childrenBeforeAnyElementFixture,
                          stringLength(childrenBeforeAnyElementFixture));
    checkThat(&failureCount, "a CHILDREN before any LEGACY tag has nothing to belong to",
              result == UI_LAYOUT_READ_UNBALANCED_CHILDREN);

    buildOverflowFixture(UI_LAYOUT_ELEMENT_LIMIT + 5U);
    result = uiLayoutRead(&description, (const Unsigned8 *)overflowFixture, stringLength(overflowFixture));
    checkThat(&failureCount, "a resource past the element limit still reads, capped", result == UI_LAYOUT_READ_OK);
    checkThat(&failureCount, "a resource past the element limit stores exactly the cap",
              description.elementCount == UI_LAYOUT_ELEMENT_LIMIT);
    checkThat(&failureCount, "the elements that did not fit are counted, not dropped silently",
              description.elementsOverflow == 5U);

    printf("%s\n", uiLayoutReadResultGetName(UI_LAYOUT_READ_OK));

    return checkSummarize(failureCount, "UI layout reader");
}
